= QWI/QWIExplorer Geography Production Docs
:nofooter:
:source-highlighter: highlightjs
Jody Hoon-Starr <jody.alexander.hoon-starr@census.gov>

link:../index.html[Back to Main Page]

== Unpack raw shapefiles

unpack data needed for QWI production

[source,bash]
----
mkdir ~/workspace/postgis_tiger/qwi_tiger_current
cd ~/workspace/postgis_tiger/qwi_tiger_current
ln -s /data/production/prod/current/extiger/us/*YYYY*{state,county,cousub,cbsa,place,tract}*gz .
gunzip *.gz -f
cd ..
----

include::../reference/geography.mdoc[tags=geo00env]

== Load shp-> db

_runtime: 2 minutes_

This program loads TIGER shapefiles into the public schema. Providing a path (/path otm) and type will load all application files expected for that type. Providing a path and single layer will load a single layer.

[source,bash]
----
time ./04_shapeloader.bash qwi_tiger_current qwi
----

== Unpack wib csvs

unpack the csv definitions

[source,bash]
----
mkdir ~/workspace/postgis_tiger/qwi_wib_csvs
cd ~/workspace/postgis_tiger/qwi_wib_csvs
ln -s /data/production/prod/current/exwib/us/*YYYY*gz .
gunzip *.gz -f
chmod u+w *.csv
cd ..
----

include::../reference/geography.mdoc[tags=geo05]

include::../reference/geography.mdoc[tags=geo06]

include::../reference/geography.mdoc[tags=geo07]

== Cleanup 

Remove unpacked files

[source,bash]
----
rm -rf ~workspace/postgis_tiger/qwi_tiger_current
rm -rf ~workspace/postgis_tiger/qwi_wib_csvs
----

include::../reference/geography.mdoc[tags=geo08]

== Remove unpopulated

_runtime: 6 minutes_

This program removes unpopulated and unused areas from the geography tables, either all tables or individual. Guam, American Samoa, and the volcanic Hawiian chain are removed. A working.invalid table is created that contains all of the geographies to be deleted. This table persists so it can be used to delete elements from the tables that created it.

The block definitions for the AK islands is now required.
Located at: ./input_data/ak_island_blocks.csv

[source,bash]
----
time ./10_removeunpopulated.bash qwi
----

== Create the formatted names

_runtime: 1 second_

Create the formatted names for all OnTheMap layers.

[source,bash]
----
time ./15_createnames.bash qwi
----

== Generate water mask

_runtime: 20 minutes_

Generate the coastal mask from the difference between the CBF and TIGER. 

IMPORTANT: The CBF layer is hardcoded as it's not released on the same schedule as tiger.
Verify the most recent CBF release and update the year reference in the program below if necessary.

[source,bash]
----
time ./17_generatecbfwatermask.bash qwi
----

== Finalize the layer tables

_runtime: 8 hours_

Create a final version of all polygon layer tables in the expected layout.

[source,bash]
----
time ./18_finalizegeo.bash qwi
----

== Export shapefiles

_runtime: 1 minute_

Export all the shapefiles for QWI and J2J. This process generates checksums and gzips the output files. 

[source,bash]
----
time ./24_export.bash /some/folder qwi
----
