dist: xenial

services:
  - docker

# safelist
branches:
  only:
  - master
  
before_install:
  - docker pull asciidoctor/docker-asciidoctor

script:
  - workdir=$(pwd)
  - docker run --rm -v $(pwd):/documents/ asciidoctor/docker-asciidoctor asciidoctor test.asciidoc

after_error: 
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

deploy:
  - provider: pages
    github-token: $GH_TOKEN 
    skip-cleanup: true
    keep-history: false
    target-branch: gh-pages
    local-dir: $workdir
    on:
        branch: master
