= LODES/OnTheMap Standard Operating Procedure
:nofooter:
:icons: font
Jody Hoon-Starr <jody.alexander.hoon-starr@census.gov>

link:../index.html[Back to Main Page]

== Unpack Faces Data

Unpack faces data needed for xwalk production

[source,bash]
----
mkdir ~/workspace/postgis_tiger/otm_tiger_current
cd ~/workspace/postgis_tiger/otm_tiger_current
ln -s /data/production/prod/current/extiger/us/tl_2018*faces*gz .
gunzip *.gz -f
cd ..
----

include::../reference/geography.mdoc[tags=geo00env]

include::../reference/geography.mdoc[tags=geo01]

include::../reference/geography.mdoc[tags=geo02]

== Unpack shapefile data

unpack the shape data needed

[source,bash]
----
cd ~/workspace/postgis_tiger/otm_tiger_current
ln -s /data/production/prod/current/extiger/us/tl_2018*{aiannh,aitsn,anrc,arealm,bg,cbsa,cd116,county,cousub,elsd,mil,necta,place,pointlm,rails,scsd,sldl,sldu,state,tract,unsd,zcta510}*gz .
gunzip *.gz -f
cd ..
----

include::../reference/geography.mdoc[tags=geo04]

== Get WIB csv

unpack the wib csv data

[source,bash]
----
mkdir wib_csvs
cd wib_csvs
ln -s /data/production/prod/current/exwib/us/*2018.csv.gz .
gunzip *.gz -f
chmod u+w *.csv
cd ..
----

include::../reference/geography.mdoc[tags=geo05]

include::../reference/geography.mdoc[tags=geo06]

include::../reference/geography.mdoc[tags=geo07]

include::../reference/geography.mdoc[tags=geo08]

include::../reference/geography.mdoc[tags=geo09]

include::../reference/geography.mdoc[tags=geo10]

include::../reference/geography.mdoc[tags=geo11]

include::../reference/geography.mdoc[tags=geo12]

include::../reference/geography.mdoc[tags=geo13]

include::../reference/geography.mdoc[tags=geo14]

== Create the formatted names

Create the formatted names for all OnTheMap layers.

[source,bash]
----
time ./15_createnames.bash otm
----

include::../reference/geography.mdoc[tags=geo16]

include::../reference/geography.mdoc[tags=geo17]

== Finalize the layer tables

Create a final version of all polygon layer tables in the expected layout.

[source,bash]
----
time ./18_finalizegeo.bash otm
----

include::../reference/geography.mdoc[tags=geo19]

include::../reference/geography.mdoc[tags=geo20]

== Load and project areawater files

Unpack the areawater shapefiles

[source,bash]
----
mkdir ~/workspace/postgis_tiger/areawaterfiles
cd ~/workspace/postgis_tiger/areawaterfiles
ln -s /data/production/prod/current/extiger/us/tl_2018*areawater*gz .
gunzip *.gz -f
cd ..
----

Load and project the areawater shapefiles in the water schema

[source,bash]
----
time ./20_lowlevelwater.bash ~/workspace/postgis_tiger/areawaterfiles
----

== Intermediate water layer

Manually create the intermediate water layer following the steps outlined in 21_manual_water_instructions.txt that is in the repository. 

Load the necessary polygons into the water schema:

[source,bash]
----
time ./22_midlevelwater.bash midlevel
----

Then manually run the following sql commands. It may be beneficiary to split some of the 
commands below into sql files and then run them in blocks since they can take a long time 
to complete. For example, putting the create table commands in temp.sql:

[source,bash]
----
psql -d otmgeo -f temp.sql
----

IMPORTANT: Replace the schemaprefix value as necessary (e.g. otm2018)

[source,SQL]
----
CREATE TABLE otm2018water.testing_snap3 AS
 SELECT (ST_Dump(ST_LineMerge(ST_SnapToGrid(ST_Union(the_geom),20)))).geom as the_geom
 FROM otm2018water.coastline;

CREATE TABLE otm2018water.testing_snap3_polys AS
 SELECT ST_MakePolygon(the_geom)
 FROM otm2018water.testing_snap3
 WHERE ST_Isclosed(the_geom);

CREATE TABLE otm2018water.testing_snap3_lines AS
 SELECT (ST_Dump(ST_LineMerge(St_Union(the_geom)))).geom as the_geom
 FROM otm2018water.testing_snap3
 WHERE NOT ST_Isclosed(the_geom);

CREATE TABLE otm2018water.testing_snap3_polys2 AS
 SELECT ST_MakePolygon(the_geom)
 FROM otm2018water.testing_snap3_lines
 WHERE ST_Isclosed(the_geom);

CREATE TABLE otm2018water.testing_snap3_lines2 AS
 SELECT (ST_Dump(ST_LineMerge(St_Union(the_geom)))).geom as the_geom
 FROM otm2018water.testing_snap3_lines
 WHERE NOT ST_Isclosed(the_geom);

CREATE TABLE otm2018water.testing_snap3_polys3 AS
 SELECT ST_MakePolygon(the_geom)
 FROM otm2018water.testing_snap3_lines2
 WHERE ST_Isclosed(the_geom);
 
CREATE TABLE otm2018water.testing_snap3_lines3 AS
 SELECT (ST_Dump(ST_LineMerge(St_Union(the_geom)))).geom as the_geom
 FROM otm2018water.testing_snap3_lines2
 WHERE NOT ST_Isclosed(the_geom);

CREATE TABLE otm2018water.coastline_polygons AS
 SELECT * FROM otm2018water.testing_snap3_polys;

INSERT INTO otm2018water.coastline_polygons
 SELECT * FROM otm2018water.testing_snap3_polys2;

INSERT INTO otm2018water.coastline_polygons
 SELECT * FROM otm2018water.testing_snap3_polys3;
 
DROP TABLE otm2018water.testing_snap3_polys3;
DROP TABLE otm2018water.testing_snap3_polys2;
DROP TABLE otm2018water.testing_snap3_polys;

ALTER TABLE otm2018water.coastline_polygons
 ADD COLUMN gid SERIAL PRIMARY KEY;

CREATE TABLE water.coastline_lines AS
 SELECT * otm2018water.testing_snap3_lines3;
 
DROP TABLE otm2018water.testing_snap3_lines3;
DROP TABLE otm2018water.testing_snap3_lines2;
DROP TABLE otm2018water.testing_snap3_lines;

ALTER TABLE otm2018water.coastline_lines
 ADD COLUMN gid SERIAL PRIMARY KEY;
----