= EM Geography Standard Operating Procedure
:nofooter:
:icons: font
:source-highlighter: highlightjs
Jody Hoon-Starr <jody.alexander.hoon-starr@census.gov>

link:../index.html[Back to Main Page]

== Overview

This process is nearly identical to the OnTheMap process as the requirements are very similar. To reduce code complexity the full set of LODES geography is used in the EM process but deleted at the end. In this way there are less chances for divergence in handling the data. These OTM attributes are dropped from the output data during export. EM specific instructions are documented below. 

== Unpack Faces Data

_runtime: x minutes_

Unpack faces data needed for xwalk production. The full set of faces and facesah are used in creating the block crosswalk files. This step loads the raw data into the database.

[source,bash]
----
mkdir ~/workspace/postgis_tiger/otm_tiger_current
cd ~/workspace/postgis_tiger/otm_tiger_current
ln -s /data/production/prod/current/extiger/us/tl_2018*faces*gz .
time gunzip *.gz -f
cd ..
----

include::../reference/geography.mdoc[tags=geo00env]

include::../reference/geography.mdoc[tags=geo01]

include::../reference/geography.mdoc[tags=geo02]

== Unpack shapefile data

_runtime: 5 minutes_

Unpack the shape data needed for processing the full suite of polygons and crosswalks. As of this writing the needed tables are identical to those required for OnTheMap although this can change and be trimmed in future iterations.

[source,bash]
----
cd ~/workspace/postgis_tiger/otm_tiger_current
ln -s /data/production/prod/current/extiger/us/tl_2018*{aiannh,aitsn,anrc,arealm,bg,cbsa,cd116,county,cousub,elsd,mil,necta,place,pointlm,rails,scsd,sldl,sldu,state,tabblock10,tract,unsd,zcta510}*gz .
time gunzip *.gz -f
cd ..
----

include::../reference/geography.mdoc[tags=geo04]

== Get WIB csv

unpack the wib csv data

[source,bash]
----
mkdir wib_csvs
cd wib_csvs
ln -s /data/production/prod/current/exwib/us/*2018.csv.gz .
gunzip *.gz -f
chmod u+w *.csv
cd ..
----

include::../reference/geography.mdoc[tags=geo05]

include::../reference/geography.mdoc[tags=geo06]

include::../reference/geography.mdoc[tags=geo07]

include::../reference/geography.mdoc[tags=geo08]

include::../reference/geography.mdoc[tags=geo09]

include::../reference/geography.mdoc[tags=geo10]

include::../reference/geography.mdoc[tags=geo11]

include::../reference/geography.mdoc[tags=geo12]

include::../reference/geography.mdoc[tags=geo13]

include::../reference/geography.mdoc[tags=geo14]

== Create the formatted names

Create the formatted names for all OnTheMap layers.

[source,bash]
----
time ./15_createnames.bash otm
----

include::../reference/geography.mdoc[tags=geo16]

== Generate water mask

_runtime: 20 minutes_

Generate the coastal mask from the difference between the CBF and TIGER. 

IMPORTANT: The CBF layer is hardcoded as it's not released on the same schedule as tiger.
Verify the most recent CBF release and update the year reference in the program below if necessary.

[source,bash]
----
time ./17_generatecbfwatermask.bash otm 
----

== Finalize the layer tables

_runtime: 1 day_

Create a final version of all polygon layer tables in the expected layout.

[source,bash]
----
time ./18_finalizegeo.bash em
----

== Export the Crosswalk CSV

Create a directory to store the final crosswalk csv and export all relevant columns.
There are a few different versions of the crosswalk available. Choose as needed.

[source,bash]
----
time ./19_exportxwalks.bash /some/folder acs_xwalk
----

== Export shapefiles

_runtime: 15 minutes_

Export all the shapefiles for EM needed by the acs_xwalk. This process generates checksums and gzips the output files. 

[source,bash]
----
time ./24_export.bash /some/folder em
----

== Deliver files to Excensus dropbox

Export all the shapefiles for EM needed by the acs_xwalk. This process generates checksums and gzips the output files. 

[source,bash]
----
rsync -avz -e "ssh -A dev ssh" ./src lehd@treehorn2:/dst
----

== Set table ownership

Once all layers are complete, hand ownership of tables over to the otmgeo user

[source,bash]
----
./00_setpermissions.bash
----
