= Production Geography QA
:nofooter:
:icons: font
:source-highlighter: highlightjs
Jody Hoon-Starr <jody.alexander.hoon-starr@census.gov>

link:../index.html[Back to Main Page]

== Overview 

This doc lays out the components that make up the LEHD geography infrastructure and QA system

== Diagram

[plantuml, diagram-classes, png]
....
@startuml
'skinparam componentStyle uml2

!define STYLE_DEFAULT_ACCENT #000
!define STYLE_DEFAULT_BGC #FFF
!define STYLE_DEFAULT_FGC #000

' Preset: Material Light Blue (200)
!define STYLE_LIGHT_ACCENT #81D4FA
!define STYLE_LIGHT_BGC #FFF
!define STYLE_LIGHT_FGC #000

' Preset: Material Light Blue (800)
!define STYLE_DARK_ACCENT #0277BD
!define STYLE_DARK_BGC #FFF
!define STYLE_DARK_FGC #000

' Preset: Material Light Blue (800)
!define STYLE_MIDNIGHT_ACCENT #0277BD
!define STYLE_MIDNIGHT_BGC #000
!define STYLE_MIDNIGHT_FGC #FFF

!define STYLE_ACCENT STYLE_DEFAULT_FGC
!define STYLE_BGC STYLE_DEFAULT_BGC
!define STYLE_FGC STYLE_DEFAULT_FGC

skinparam {

    ' Global Options
    DPI 200
    Shadowing false
    DefaultFontName Roboto Condensed
    DefaultMonospacedFontName Inconsolata
    DefaultFontColor STYLE_FGC

    ' Styles - Borders

    ArrowColor STYLE_ACCENT
    ActivityBorderColor STYLE_ACCENT
    ActivityDiamondBorderColor STYLE_ACCENT
    ActorBorderColor STYLE_ACCENT
    AgentBorderColor STYLE_ACCENT
    ArtifactBorderColor STYLE_ACCENT
    BoundaryBorderColor STYLE_ACCENT
    ClassBorderColor STYLE_ACCENT
    CloudBorderColor STYLE_ACCENT
    CollectionsBorderColor STYLE_ACCENT
    ComponentBorderColor STYLE_ACCENT
    ControlBorderColor STYLE_ACCENT
    DatabaseBorderColor STYLE_ACCENT
    EntityBorderColor STYLE_ACCENT
    FileBorderColor STYLE_ACCENT
    FolderBorderColor STYLE_ACCENT
    FrameBorderColor STYLE_ACCENT
    InterfaceBorderColor STYLE_ACCENT
    LegendBorderColor STYLE_ACCENT
    NodeBorderColor STYLE_ACCENT
    NoteBorderColor STYLE_ACCENT
    ObjectBorderColor STYLE_ACCENT
    PackageBorderColor STYLE_ACCENT
    ParticipantBorderColor STYLE_ACCENT
    PartitionBorderColor STYLE_ACCENT
    QueueBorderColor STYLE_ACCENT
    RectangleBorderColor STYLE_ACCENT
    SequenceBoxBorderColor STYLE_ACCENT
    SequenceDividerBorderColor STYLE_ACCENT
    SequenceGroupBorderColor STYLE_ACCENT
    SequenceLifeLineBorderColor STYLE_ACCENT
    SequenceReferenceBorderColor STYLE_ACCENT
    StackBorderColor STYLE_ACCENT
    StateBorderColor STYLE_ACCENT
    StorageBorderColor STYLE_ACCENT
    SwimlaneBorderColor STYLE_ACCENT
    UsecaseBorderColor STYLE_ACCENT

    ' Styles - Backgrounds

    ActivityBackgroundColor STYLE_BGC
    ActivityDiamondBackgroundColor STYLE_BGC
    ActorBackgroundColor STYLE_BGC
    AgentBackgroundColor STYLE_BGC
    ArtifactBackgroundColor STYLE_BGC
    BackgroundColor STYLE_BGC
    BoundaryBackgroundColor STYLE_BGC
    ClassBackgroundColor STYLE_BGC
    ClassHeaderBackgroundColor STYLE_BGC
    CloudBackgroundColor STYLE_BGC
    CollectionsBackgroundColor STYLE_BGC
    ComponentBackgroundColor STYLE_BGC
    ControlBackgroundColor STYLE_BGC
    DatabaseBackgroundColor STYLE_BGC
    EntityBackgroundColor STYLE_BGC
    FileBackgroundColor STYLE_BGC
    FolderBackgroundColor STYLE_BGC
    FrameBackgroundColor STYLE_BGC
    IconPackageBackgroundColor STYLE_BGC
    IconPrivateBackgroundColor STYLE_BGC
    IconProtectedBackgroundColor STYLE_BGC
    IconPublicBackgroundColor STYLE_BGC
    InterfaceBackgroundColor STYLE_BGC
    LegendBackgroundColor STYLE_BGC
    NodeBackgroundColor STYLE_BGC
    NoteBackgroundColor STYLE_BGC
    ObjectBackgroundColor STYLE_BGC
    PackageBackgroundColor STYLE_BGC
    ParticipantBackgroundColor STYLE_BGC
    PartitionBackgroundColor STYLE_BGC
    QueueBackgroundColor STYLE_BGC
    RectangleBackgroundColor STYLE_BGC
    SequenceBoxBackgroundColor STYLE_BGC
    SequenceDividerBackgroundColor STYLE_BGC
    SequenceGroupBackgroundColor STYLE_BGC
    SequenceGroupBodyBackgroundColor STYLE_BGC
    SequenceLifeLineBackgroundColor STYLE_BGC
    SequenceReferenceBackgroundColor STYLE_BGC
    SequenceReferenceHeaderBackgroundColor STYLE_BGC
    StackBackgroundColor STYLE_BGC
    StateBackgroundColor STYLE_BGC
    StereotypeABackgroundColor STYLE_BGC
    StereotypeCBackgroundColor STYLE_BGC
    StereotypeEBackgroundColor STYLE_BGC
    StereotypeIBackgroundColor STYLE_BGC
    StereotypeNBackgroundColor STYLE_BGC
    StorageBackgroundColor STYLE_BGC
    TitleBackgroundColor STYLE_BGC
    UsecaseBackgroundColor STYLE_BGC

    ' -=- END OF RECOMMENDED STYLE -=-

    ' Other Settings
    ' These settings are included in the language specs, but
    ' it's not recommended to be applied.

        'TitleBorderColor STYLE_ACCENT
        'DiagramBorderColor STYLE_ACCENT

    ' CUSTOM STYLE
    ' All items below can be safely commented out.
    ' This will override the options listed above.
    roundcorner 8
    'Monochrome true

    NoteFontName Roboto Condensed
    NoteFontStyle Italic
    'NoteBackgroundColor STYLE_BGC
}
cloud {
  [geo division] -- ftp
  [geo division] -- dmsdelivery
  [state input] -- wibdefinition
}

node "external process" {
  [extiger] 
  [exwib] 
  [exgrf] 
  [exmaf]
}
 
node "formatting process" {
 [tiger] 
 [wib] 
 [grf] 
 [maf]
} 
 
database "appgeo db" {
 [shps]
 [xwalks]
 node "db qa" STYLE_MIDNIGHT_ACCENT {
  [module qa]
 } 
}

node "inline qa" STYLE_MIDNIGHT_ACCENT {
 [tigerqa] 
 [wibqa] 
 [grfqa] 
 [mafqa]
} 

node "non-pu process" {
 [pubgeo]
 [gal]
} 

node "pu process" {
 [j2j]
 [qwi]
 [lodes]
} 

node "pu qa" STYLE_MIDNIGHT_ACCENT {
 [j2jqa]
 [qwiqa]
 [lodesqa]
} 

ftp -- [extiger]
dmsdelivery -- [exgrf] 
dmsdelivery -- [exmaf] 
wibdefinition -- [exwib]

[extiger] -- [tiger]
[extiger] -- [shps]
[extiger] -- [xwalks]
[exwib] -- [shps]
[exwib] -- [xwalks]
[exwib] -- [wib]
[exgrf] -- [grf]
[exmaf] -- [maf]

[tiger] -- [tigerqa]
[wib] -- [wibqa]
[grf] -- [grfqa]
[maf] -- [mafqa]

[shps] -- [module qa]
[xwalks] -- [module qa]

[wibqa] -- [pubgeo]
[grfqa] -- [pubgeo]
[tigerqa] -- [gal]
[wibqa] -- [gal]
[grfqa] -- [gal]
[mafqa] -- [gal]

[gal] -- [qwi]
[pubgeo] -- [qwi]
[module qa] -- [lodes]

[lodes] -- [lodesqa]
[qwi] -- [qwiqa]
[j2j] -- [j2jqa]

@enduml
....
